version: '3'
services:
    api:
        build: backend/.
        ports:
            - "8080:8080"
    frontend:
        build: frontend/dev/.
        ports:
            - "4200:4200"
        depends_on:
            - api